### ISSUE TITLE
line break not working

### ISSUE THREAD

**Issue by MichalStefanic** [matthiaskoenig/libsbgn-python#30]
Hi, 

I am trying to use `libsbgnpy` library in my project, everything is working good, but line break is not working.
If I read xml file and then render image it's working good, but in case I will create glyph, using library and add into label text attribute with `&#xA;` like this: 
```
g = libsbgn.glyph(class_=GlyphClass.MACROMOLECULE, id='glyph1')
g.set_label(libsbgn.label(text='structured&#xA;protein'))
g.set_bbox(libsbgn.bbox(x=40, y=120, w=60, h=60))
map.add_glyph(g)
```

it's not working and in final image is `structured&#xA;protein`, instead of 
`structured`
`protein`

Is it bug or I'm just using it in wrong way?

I'm using mac os and python 3.6.5

**Comment by matthiaskoenig** [comment]
Hi @MichalStefanic ,
did you try '\n' as linebreak, i.e. 
```
text='structured\nprotein'
```
Also which software are you using for rendering the SBGN? I am not sure what the official character for newlines in labels is in SBGN. This sounds more like a rendering issue to me, i.e. you have to find out which character your SBGN software is using for newlines (but should be the same for all software otherwise is not standardized).
If the `\n` is not solving your issue, I will post a question on the SBGN list?

Best Matthias

**Comment by MichalStefanic** [comment]
Hi @matthiaskoenig,

it's working with `\n`. I don't even used this standard line break, because I followed the documentation in [code](https://github.com/matthiaskoenig/libsbgn-python/blob/develop/libsbgnpy/libsbgn.py#L1112), where line breaks are encoded as `&#xA;`.

So I guess, we can close this issue, thanks, You helped me a lot. :-)

Have a nice day.

Michal
